name: hades
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
  - ehmoussi
dependencies:
  - python=3.8
  - setuptools=59.5.0
  - pip=24.0
  - openmm=7.5.1
  - pdbfixer=1.7
  - einops=0.6.1
  - fairscale=0.4.3
  - omegaconf=2.3.0
  - hydra-core=1.3.2
  - pandas=1.3.5
  - pytest=7.4.4
  - biotite=0.31.0
  - hmmer=3.3.2
  - hhsuite=3.3.0
  - kalign2=2.04
  - pytorch=1.12.1
  - cudatoolkit=11.3.1
  - gxx_linux-64=7.3.0
  - xlsxwriter
  - pip
  - pip:
      - biopython==1.79
      - deepspeed==0.5.9
      - dm-tree==0.1.6
      - ml-collections==0.1.0
      - numpy==1.21.2
      - pyyaml==5.4.1
      - requests==2.26.0
      - scipy==1.7.1
      - tqdm==4.62.2
      - typing-extensions==4.7.1
      - pytorch-lightning==1.5.10
      - wandb==0.12.21
      - git+https://github.com/NVIDIA/dllogger.git
      - git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307
      - fair-esm[esmfold]
      - tape_proteins==0.5
      - sequence-models==1.2.0
      - pyrosetta-installer # followed by bash```python -c 'import pyrosetta_installer; pyrosetta_installer.install_pyrosetta()'```